function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/house"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 5
d_block = 864
dropout = 0.0

[base_config.optimizer]
type = "AdamW"
lr = 0.0036103847293236387
weight_decay = 0.04322500663292513
