function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/ecom-offers"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 256
dropout = 0.0

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 124

[base_config.optimizer]
type = "AdamW"
lr = 5.7961497306153224e-05
weight_decay = 0.20475436880578468
