function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/cooking-time"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 2
d_block = 592
dropout = 0.01941146468820265

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 38

[base_config.optimizer]
type = "AdamW"
lr = 0.00231821456062835
weight_decay = 0.15591718030312787
