function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/ecom-offers"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 720
dropout = 0.0

[base_config.optimizer]
type = "Muon"
ema_decay = 0.9066373309461611
betas = [
    0.9,
    0.999,
]
eps = 1e-08
lr = 3.369582278490842e-05
weight_decay = 0.06448347955013337

[base_config.optimizer.muon]
lr = 0.0009357613713794432
