function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 3
d_block = 720
dropout = 0.10741237270536619

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 28

[base_config.optimizer]
type = "Muon"
lr = 0.0008255881046532107
weight_decay = 0.0030879444786151675
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.02072929927840135
