function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/weather"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 832
dropout = 0.08799811571867723

[base_config.optimizer]
type = "NAdam"
lr = 0.0002958953194872096
decoupled_weight_decay = true
weight_decay = 0.5782502506377077
