function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/higgs-small"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 352
dropout = 0.1649998347874684

[base_config.optimizer]
type = "AdamWScheduleFree"
lr = 0.0021564117805348295
weight_decay = 2.571073562262473
