function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/weather"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 800
dropout = 0.18568619452382545

[base_config.optimizer]
type = "SOAP"
lr = 0.00020277815202971345
weight_decay = 0.757670454582501
