function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 3
d_block = 384
dropout = 0.1576682778802874

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.965205475269209
lr = 0.004416133665871451
weight_decay = 0.03388554271765694
