function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 624
dropout = 0.340665355114904

[base_config.optimizer]
lr = 6.336691681157898e-05
weight_decay = 0.07461789087353458
betas = [
    0.9,
    0.999,
]
eps = 1e-08
type = "Muon"

[base_config.optimizer.muon]
lr = 0.0018963909890200247
