function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 2
d_block = 992
dropout = 0.26348825299410045

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 37

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9643878182002066
lr = 0.0025806846145479127
weight_decay = 0.001104980769896112
