function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/cooking-time"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 816
dropout = 0.19093146638716274

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.98979320574353
lr = 3.993905521055839e-05
weight_decay = 1.9335521153512316
