function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/maps-routing"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 496
dropout = 0.49349881323445177

[base_config.optimizer]
type = "Signum"
lr = 3.850763397011797e-05
weight_decay = 4.911335892258066
