function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 176
dropout = 0.4315966995853842

[base_config.optimizer]
type = "ADOPT"
decouple = true
lr = 0.0005655689936837091
weight_decay = 4.96132041093967
