function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/ecom-offers"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 1
d_block = 512
dropout = 0.0

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 2

[base_config.optimizer]
type = "AdamW"
lr = 0.00010053658924221453
weight_decay = 0.008069492432379267
