function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/maps-routing"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 1
d_block = 784
dropout = 0.0

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 2

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9361149176882629
lr = 0.0005637702257102428
weight_decay = 0.015676809044622368
