function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/delivery-eta"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 960
dropout = 0.44872079050854574

[base_config.optimizer]
type = "Signum"
lr = 1.5885940451636188e-05
weight_decay = 3.2921667457897126
