function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/maps-routing"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 1
d_block = 848
dropout = 0.0

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 75

[base_config.optimizer]
type = "Muon"
lr = 0.00011541914404905026
weight_decay = 0.09548943410499022
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.06170684557298898
