function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/microsoft"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 2
d_block = 320
dropout = 0.026383658787159925

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 2

[base_config.optimizer]
type = "AdamW"
lr = 0.001982489578476263
weight_decay = 0.008243714149957187
