function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 448
dropout = 0.4192545758270336

[base_config.optimizer]
type = "C-AdamW"
lr = 0.0003464311178429917
weight_decay = 0.7096326020660232
