function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 992
dropout = 0.23859451101845391

[base_config.optimizer]
type = "SOAP"
lr = 0.0001823799901962267
weight_decay = 0.22713400921163399
