function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/maps-routing"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 752
dropout = 0.33130009897554824

[base_config.optimizer]
type = "AdEMAMix"
lr = 0.00012225389054470982
alpha = 6.050694169092862
weight_decay = 3.958943016008069
