function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/house"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 592
dropout = 0.3824018554206633

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 11

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9911981997347666
lr = 0.0005226109541490121
weight_decay = 2.267951874446326
