function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/homecredit-default"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 784
dropout = 0.22338213839821425

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 92

[base_config.optimizer]
type = "Muon"
lr = 3.948596681604474e-05
weight_decay = 0.037612915922029866
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.00027893666929146337
