function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/diamond"
num_policy = "noisy-quantile"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 3
d_block = 160
dropout = 0.0729199918593292

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9540588556864668
lr = 0.0011926663704447346
weight_decay = 0.027748243281929777
