function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/adult"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 6
d_block = 480
dropout = 0.0

[base_config.optimizer]
type = "Muon"
ema_decay = 0.9018847568044259
betas = [
    0.9,
    0.999,
]
eps = 1e-08
lr = 0.0009289212756392082
weight_decay = 0.02106492597921237

[base_config.optimizer.muon]
lr = 0.00014030579962869731
