function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/homesite-insurance"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 976
dropout = 0.4213348817087741

[base_config.optimizer]
type = "AdEMAMix"
lr = 0.00039667503202376074
alpha = 3.4138378955590767
weight_decay = 3.831252114786293
