function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/homecredit-default"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 928
dropout = 0.14815392762686883

[base_config.optimizer]
type = "AdamWScheduleFree"
lr = 0.01781608079167978
weight_decay = 1.2735789251893384
