function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 656
dropout = 0.4290660239396198

[base_config.optimizer]
type = "Signum"
lr = 0.0001344435299288758
weight_decay = 1.5573308489611308
