function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/ecom-offers"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 3
d_block = 496
dropout = 0.4877607525014429

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 3

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9344536992457034
lr = 0.001738729685778683
weight_decay = 0.00327257065512027
