function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/black-friday"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 688
dropout = 0.3387657581941987

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9714915000765743
lr = 0.0002710156550781729
weight_decay = 0.34293517346847674
