function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm-packed"
n_blocks = 3
d_block = 688
dropout = 0.0

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9834778360749751
lr = 0.0007934410562707478
weight_decay = 0.05450096584611277
