function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 912
dropout = 0.31587230044559206

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 95

[base_config.optimizer]
type = "Muon"
lr = 0.0002667408436321994
weight_decay = 0.018373419407409934
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.0009916782454789082
