function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/adult"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 5
d_block = 912
dropout = 0.462396750021339

[base_config.optimizer]
type = "NAdam"
lr = 6.562880442741544e-05
decoupled_weight_decay = true
weight_decay = 1.0247242610206924
