function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/house"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 864
dropout = 0.3468810674572692

[base_config.optimizer]
type = "AdaBelief"
lr = 0.0002425359200031407
weight_decay = 1.3224842815373237
