function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/microsoft"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 848
dropout = 0.163648855788841

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.992893030110068
lr = 3.636060768379974e-05
weight_decay = 3.166039558675447
