function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm-packed"
k = 16
n_blocks = 3
d_block = 256
dropout = 0.0

[base_config.optimizer]
type = "Muon"
lr = 0.002588428446195889
weight_decay = 0.034764611286213415
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.03585802046464568
