function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/cooking-time"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm-packed"
n_blocks = 2
d_block = 80
dropout = 0.0

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9481152636119479
lr = 0.00024984576876947305
weight_decay = 0.005416885761317713
