function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/black-friday"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 448
dropout = 0.24414649381400022

[base_config.optimizer]
type = "AdEMAMix"
lr = 0.00010593938600548286
alpha = 4.645021196880912
weight_decay = 2.186657332389385
