function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/homecredit-default"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 288
dropout = 0.4837714111435973

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 117

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9182678304394515
lr = 0.0001111965738889667
weight_decay = 0.010067570323499465
