function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/homesite-insurance"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 3
d_block = 464
dropout = 0.22807516610827427

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 4

[base_config.optimizer]
type = "Muon"
lr = 0.001120325401917855
weight_decay = 0.06859416411328696
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.017134364197119667
