function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/adult"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 6
d_block = 752
dropout = 0.43253489709832516

[base_config.optimizer]
type = "ADOPT"
decouple = true
lr = 4.046367068566307e-05
weight_decay = 0.045983602291267925
