function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 224
dropout = 0.23173907152904247

[base_config.optimizer]
type = "AdaBelief"
lr = 0.0005038230299980382
weight_decay = 0.2582740772698841
