function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 976
dropout = 0.4528560950823442

[base_config.optimizer]
type = "Signum"
lr = 4.715299972040624e-05
weight_decay = 0.6462013747061497
