function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/black-friday"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 1008
dropout = 0.3925419065365402

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 95

[base_config.optimizer]
type = "AdamW"
lr = 0.00017079789592742953
weight_decay = 0.026707771359404834
