function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 6
d_block = 960
dropout = 0.20002552273779925

[base_config.optimizer]
type = "SGD"
momentum = 0.9
dampening = 0.9
lr = 0.032657268295082635
weight_decay = 0.005002888869003617
