function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/diamond"
num_policy = "noisy-quantile"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 6
d_block = 320
dropout = 0.19449982823833115

[base_config.optimizer]
type = "Adan"
lr = 0.0005459013227708854
weight_decay = 0.45837183518901237
