function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/homecredit-default"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 3
d_block = 976
dropout = 0.42116007186096066

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 112

[base_config.optimizer]
type = "Muon"
lr = 0.00012905256272180302
weight_decay = 0.001997563765705353
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.00292488881675298
