function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/maps-routing"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 304
dropout = 0.4885173535417667

[base_config.optimizer]
type = "RAdam"
decoupled_weight_decay = true
lr = 3.250967301655816e-05
weight_decay = 0.34730164482044373
