function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 5
d_block = 368
dropout = 0.4973207617352513

[base_config.optimizer]
type = "AdamW"
lr = 0.00010447870956388176
weight_decay = 0.8673565579602179
