function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/microsoft"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 528
dropout = 0.3825506238264811

[base_config.optimizer]
type = "AdEMAMix"
lr = 7.758874343485346e-05
alpha = 4.694618636361991
weight_decay = 1.6353041948419265
