function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/homesite-insurance"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 576
dropout = 0.1938636601520483

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 26

[base_config.optimizer]
type = "AdamW"
lr = 0.000789135345204577
weight_decay = 2.1006488815111544
