function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/higgs-small"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 304
dropout = 0.4602031742977478

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 94

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.992353086377973
lr = 0.000502836167964326
weight_decay = 2.7587204746241545
