function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/churn"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 320
dropout = 0.40003140722748165

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 7

[base_config.optimizer]
type = "Muon"
lr = 0.0005978934351472793
weight_decay = 0.06262740834355757
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.007634611562671512
