function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/homesite-insurance"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 304
dropout = 0.18722833357875573

[base_config.optimizer]
type = "RAdam"
decoupled_weight_decay = true
lr = 7.81491692717033e-05
weight_decay = 0.5426294493433236
