function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/weather"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 848
dropout = 0.13791435695371942

[base_config.optimizer]
type = "Adan"
lr = 0.00011003659772266837
weight_decay = 0.6099789803555107
