function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 928
dropout = 0.44959317757158124

[base_config.optimizer]
type = "AdamW"
lr = 0.0007277551314107305
weight_decay = 0.01343835317956047
