function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/house"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 592
dropout = 0.20562508797316686

[base_config.optimizer]
type = "ADOPT"
decouple = true
lr = 5.930957732154186e-05
weight_decay = 4.888334154175763
