function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/homesite-insurance"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 624
dropout = 0.48689681517754335

[base_config.optimizer]
type = "AdamWScheduleFree"
lr = 0.008729811692592186
weight_decay = 0.5394021861962345
