function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 992
dropout = 0.4268737916067027

[base_config.optimizer]
type = "RAdam"
decoupled_weight_decay = true
lr = 0.00028079583776375905
weight_decay = 0.14428257616627024
