function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 528
dropout = 0.3225434489871671

[base_config.optimizer]
type = "Lion"
lr = 0.00014100198321448848
weight_decay = 1.9819954159528288
