function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 4
d_block = 896
dropout = 0.13880943515294678

[base_config.optimizer]
type = "Muon"
lr = 0.0019728641921231724
weight_decay = 0.025009491138050687
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.007345939692327789
