function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/higgs-small"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 384
dropout = 0.49310554730079925

[base_config.optimizer]
type = "Lion"
lr = 0.0001349150760522747
weight_decay = 2.725598057895562
