function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/adult"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 4
d_block = 112
dropout = 0.4387170916895204

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 119

[base_config.optimizer]
type = "AdamW"
lr = 0.00039671040625932185
weight_decay = 0.19562175643109905
