function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/adult"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 6
d_block = 1008
dropout = 0.47774646657415987

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9832561686566148
lr = 0.00016577499781898547
weight_decay = 3.9769327252118245
