function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/microsoft"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 592
dropout = 0.1720377103968323

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 4

[base_config.optimizer]
type = "Muon"
lr = 6.692182128847311e-05
weight_decay = 0.1529682709869441
betas = [
    0.9,
    0.999,
]
eps = 1e-08

[base_config.optimizer.muon]
lr = 0.00015285888069916967
