function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/higgs-small"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 6
d_block = 192
dropout = 0.2810894347814642

[base_config.optimizer]
type = "RAdam"
decoupled_weight_decay = true
lr = 0.0005378319640166516
weight_decay = 0.11335137663090887
