function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/diamond"
num_policy = "noisy-quantile"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 160
dropout = 0.0

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 116

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9380055490492524
lr = 0.0007661012274940911
weight_decay = 0.03534574650322806
