function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/homecredit-default"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm-packed"
n_blocks = 5
d_block = 688
dropout = 0.4312214204438886

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9320708625736022
lr = 0.002202952225533011
weight_decay = 0.1487724988529729
