function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/higgs-small"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 224
dropout = 0.421094945801464

[base_config.optimizer]
type = "AdaBelief"
lr = 0.00045419130627084853
weight_decay = 0.2540875797230737
