function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/churn"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 592
dropout = 0.0

[base_config.optimizer]
type = "Signum"
lr = 0.0004928290464913843
weight_decay = 2.3638046718864634
