function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/cooking-time"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 608
dropout = 0.43977863966076036

[base_config.optimizer]
type = "Lion"
lr = 8.253068047345468e-05
weight_decay = 0.04027784374464663
