function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
share_training_batches = false
save_checkpoint = false

[base_config.data]
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
arch_type = "tabm"
k = 16
n_blocks = 2
d_block = 1024
dropout = 0.1924331905986025

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 73

[base_config.optimizer]
type = "AdamW"
lr = 0.0031746855994273164
weight_decay = 0.2681602943934688
