function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 3
d_block = 912
dropout = 0.28985244104410635

[base_config.model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16
activation = false
version = "B"

[base_config.model_num_embeddings_bins]
n_bins = 89

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9322001170081535
lr = 0.0030395225305205557
weight_decay = 0.003050984714300598
