function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 1024
dropout = 0.44299117472782173

[base_config.optimizer]
type = "Adan"
lr = 0.0002810109769750074
weight_decay = 0.48781841871405374
