function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 992
dropout = 0.0

[base_config.optimizer]
lr = 5.6119765680400325e-05
weight_decay = 0.685310610775367
betas = [
    0.9,
    0.999,
]
eps = 1e-08
type = "Muon"

[base_config.optimizer.muon]
lr = 0.0006218258375043386
