function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/california"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 464
dropout = 0.40350513715787256

[base_config.optimizer]
type = "NAdam"
lr = 0.0007658321873806677
decoupled_weight_decay = true
weight_decay = 0.36561299641447337
