function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false
share_training_batches = false

[base_config.data]
path = "data/otto"
cache = true

[base_config.model]
type = "tabm"

[base_config.model.backbone]
k = 16
arch_type = "tabm"
n_blocks = 3
d_block = 816
dropout = 0.24633371437800253

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9959594931093185
lr = 0.0019678387872159885
weight_decay = 0.0030885740525548678
