function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 1024
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/microsoft"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 2
d_block = 960
dropout = 0.4850598978994089

[base_config.optimizer]
type = "RAdam"
decoupled_weight_decay = true
lr = 3.8284441018406095e-05
weight_decay = 0.352890060863827
