function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/higgs-small"
num_policy = "noisy-quantile"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 144
dropout = 0.3819600801162935

[base_config.optimizer]
type = "ADOPT"
decouple = true
lr = 0.0007687440969039841
weight_decay = 0.026975866171232273
