function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/black-friday"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 3
d_block = 576
dropout = 0.418394527145151

[base_config.optimizer]
type = "AdaBelief"
lr = 0.00011188585326418487
weight_decay = 0.4006604388120993
