function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/diamond"
num_policy = "noisy-quantile"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 5
d_block = 848
dropout = 0.31037142093322273

[base_config.optimizer]
type = "AdamW"
ema_decay = 0.9010232423519035
lr = 0.0001839380709712607
weight_decay = 3.5860565448557358
