function = "bin.ffn.main"
n_seeds = 10
n_workers = 2

[base_config]
batch_size = 512
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/diamond"
num_policy = "noisy-quantile"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 5
d_block = 592
dropout = 0.17887286719939677

[base_config.optimizer]
type = "NAdam"
lr = 3.0050216554817422e-05
decoupled_weight_decay = true
weight_decay = 3.0473754037830627
