function = "bin.ffn.main"
n_seeds = 10

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0
save_checkpoint = false

[base_config.data]
path = "data/churn"
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
type = "mlp"

[base_config.model.backbone]
n_blocks = 1
d_block = 432
dropout = 0.0

[base_config.optimizer]
type = "Muon"
ema_decay = 0.9153034585391592
betas = [
    0.9,
    0.999,
]
eps = 1e-08
lr = 0.0008978578907321493
weight_decay = 0.43886229713434705

[base_config.optimizer.muon]
lr = 0.014413486906877467
